// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-hGV6wZ5IbAHOC9txEzbinel0NE9Rw5I',
    appId: '1:152771674386:web:f6d768dc4c6453c5e473cb',
    messagingSenderId: '152771674386',
    projectId: 'vocalib-a1189',
    authDomain: 'vocalib-a1189.firebaseapp.com',
    storageBucket: 'vocalib-a1189.firebasestorage.app',
    measurementId: 'G-VSFZZ4PNV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRD0adK1UVukutGtDiPggfa5cedu-oeng',
    appId: '1:152771674386:android:158eb40796b14e58e473cb',
    messagingSenderId: '152771674386',
    projectId: 'vocalib-a1189',
    storageBucket: 'vocalib-a1189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkH9eOhfXu0meqTI9wfYZ3ZV-5dB5OkTc',
    appId: '1:152771674386:ios:41d3b8df29ce783ae473cb',
    messagingSenderId: '152771674386',
    projectId: 'vocalib-a1189',
    storageBucket: 'vocalib-a1189.firebasestorage.app',
    iosBundleId: 'com.example.vocalibb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkH9eOhfXu0meqTI9wfYZ3ZV-5dB5OkTc',
    appId: '1:152771674386:ios:41d3b8df29ce783ae473cb',
    messagingSenderId: '152771674386',
    projectId: 'vocalib-a1189',
    storageBucket: 'vocalib-a1189.firebasestorage.app',
    iosBundleId: 'com.example.vocalibb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-hGV6wZ5IbAHOC9txEzbinel0NE9Rw5I',
    appId: '1:152771674386:web:77b9ea746848e978e473cb',
    messagingSenderId: '152771674386',
    projectId: 'vocalib-a1189',
    authDomain: 'vocalib-a1189.firebaseapp.com',
    storageBucket: 'vocalib-a1189.firebasestorage.app',
    measurementId: 'G-BT9T1841Q7',
  );
}
